export default [{
  id:0,
  img:"https://s3.ap-south-1.amazonaws.com/kalvi-education.github.io/pizza-react.jpg",
  name:"pizza",
  cal:266,
},
{
  id:1,
  img:"https://s3.ap-south-1.amazonaws.com/kalvi-education.github.io/applie-react.jpeg",
  name:"apple",
  cal:52,
},
{
  id:3,
  img:"https://s3.ap-south-1.amazonaws.com/kalvi-education.github.io/orange-react.jpeg",
  name:"oranges",
  cal:47,
},
{
  id:4,
  img:"https://s3.ap-south-1.amazonaws.com/kalvi-education.github.io/almonds-react.jpeg",
  name:"almonds",
  cal:7,
},
{
  id:5,
  img:"https://s3.ap-south-1.amazonaws.com/kalvi-education.github.io/burger-react.jpeg",
  name:"burger",
  cal:295,
},

]
